Add sample with version diff application
ktorio/ktor-samples pull request #105
Opened 2021-11-12 15:42 UTC by e5l

2021-11-15 13:52 UTC, rsinukov approved these changes

2021-11-26 14:29 UTC, andreyaksenov requested changes

2021-11-26 14:29 UTC, andreyaksenov commented on README.md
>    with [Ktor](https://ktor.io) and [WebSockets](https://ktor.io/docs/websocket.html).
> A reverse proxy application written using [Ktor](https://ktor.io) and [WebSockets](https://ktor.io/docs/websocket.html).

2021-11-26 14:29 UTC, andreyaksenov commented on README.md
>  * [youkube](youkube/README.md) - Video upload/view application written with [Ktor](https://ktor.io).
> A video upload/view application ...

2021-11-26 14:29 UTC, andreyaksenov commented on README.md
> +* [version-diff](version-diff/README.md) - Application showing diff between artifact in 2 versions of project.
> An application showing the difference between artifacts in two versions of a project.

2021-11-26 14:29 UTC, andreyaksenov commented on version-diff/README.md
> +Diff tool for maven artifacts written using [Ktor](https://ktor.io) client.
> A diff tool for Maven artifacts written using [Ktor](https://ktor.io) client.

2021-11-26 14:29 UTC, andreyaksenov commented on version-diff/README.md
> +Execute this command in the sample directory:
> Execute this command in a sample's directory:

2021-12-01 11:11 UTC, e5l commented on README.md
>    with [Ktor](https://ktor.io) and [WebSockets](https://ktor.io/docs/websocket.html).
Thanks, fixed

2021-12-01 11:11 UTC, e5l commented on README.md
>  * [youkube](youkube/README.md) - Video upload/view application written with [Ktor](https://ktor.io).
Fixed

2021-12-01 11:14 UTC, e5l commented on README.md
> +* [version-diff](version-diff/README.md) - Application showing diff between artifact in 2 versions of project.
Thank you, fixed

2021-12-01 11:14 UTC, e5l commented on version-diff/README.md
> +Diff tool for maven artifacts written using [Ktor](https://ktor.io) client.
Yep, fixed!

2021-12-01 11:15 UTC, e5l commented on version-diff/README.md
> +Execute this command in the sample directory:
Fixed

2021-12-01 11:15 UTC, e5l commented
Hey @andreyaksenov, thanks for the review. All fixed! Could you take a look?

2021-12-01 11:24 UTC, andreyaksenov approved these changes

2021-12-01 11:25 UTC, merged