Vgoncharova/mvc
ktorio/ktor-samples pull request #184
Opened 2023-12-20 15:35 UTC by VGoncharova

Wishlist application for adding and removing wishes to Wishlist that uses FreeMarker templates and Exposed

2024-01-09 13:39 UTC, e5l requested changes
Hey @VGoncharova, good job!

Could you please address the comments?


@vnikolova, please also take a look

2024-01-09 13:39 UTC, e5l commented on mvc-web/build.gradle.kts
> +    implementation("com.h2database:h2:2.1.214")
Could you please extract the version in the properties file?

2024-01-09 13:39 UTC, e5l commented on mvc-web/src/main/kotlin/com/example/model/DatabaseFactory.kt
> +        val driverClassName = "org.h2.Driver"
Please move the DB configuration keys to the `application.yaml` or `application.properties`

2024-01-10 09:42 UTC, vnikolova requested changes
Nice example! Just a few details that need updating :)

2024-01-10 09:42 UTC, vnikolova commented on mvc-web/README.md
> +Then, navigate to [http://localhost:8080/](http://localhost:8080/) to see the sample home page.localhost:8080/](http://localhost:8080/) in a browser to create, edit, and delete articles.
There's nothing at http://localhost:8080/. This line should say:

"Then, navigate to the following pages:
- [http://localhost:8080/wish/list](http://localhost:8080/wish/list) to view and modify the wishlist. 
- [http://localhost:8080/wish/topwishes](http://localhost:8080/wish/topwishes) to see the top three wishes in the list."

2024-01-10 09:42 UTC, vnikolova commented on mvc-web/src/main/kotlin/com/example/model/DatabaseFactory.kt
> +object DatabaseFactory {
In other examples, we renamed "DatabaseFactory" to "DatabaseSingleton". I think we should keep the names consistent.

2024-01-10 09:42 UTC, vnikolova commented on mvc-web/README.md
> +# MVC application for Ktor
"MVC application with Ktor Server"

2024-01-10 09:42 UTC, vnikolova commented on mvc-web/src/test/kotlin/com/example/ApplicationTest.kt
> +        client.get("/").apply {
This test would fail. Can we either remove it or add another valid test?

2024-01-11 17:34 UTC, vnikolova approved these changes
Looks good!

2024-01-12 12:08 UTC, e5l approved these changes
lgtm

2024-01-15 07:49 UTC, merged