docs-split
ktorio/ktor-samples pull request #78
Opened 2020-08-27 14:10 UTC by hhariri

Removing MPP, Full-stack and Doc samples.

2020-08-27 14:28 UTC, e5l requested changes
lgtm. Could you check the `ktor.io` website to remove mentions of removed samples(for instance: https://ktor.io/servers/uploads.html has youkube reference)?

2020-08-28 07:57 UTC, Stexxe approved these changes

2020-08-28 08:56 UTC, Stexxe requested changes
Please create an associated Youtrack issue.

2020-08-28 08:57 UTC, e5l approved these changes

2020-08-28 09:01 UTC, merged